let HUYA = require('./HUYA');

let TafMx = {};

TafMx.UriMapping = TafMx.UriMapping || {};
TafMx.WupMapping = TafMx.WupMapping || {};
TafMx.NoLog = TafMx.NoLog || {};
Object.assign(TafMx.UriMapping, {
    1001: HUYA.NobleNotice,
    1002: HUYA.NobleEnterNotice,
    1005: HUYA.NobleEnterNotice,
    1006: HUYA.NobleLevelNotice,
    1400: HUYA.MessageNotice,
    1420: HUYA.ExpressionEmoticonNotice,
    3104: HUYA.SubscribeInfoNotify,
    6100: HUYA.WeekStarPropsIds,
    6102: HUYA.WeekStarPropsIdsTab,
    6110: HUYA.VipEnterBanner,
    6200: HUYA.EnterPushInfo,
    6201: HUYA.GameAdvertisement,
    6202: HUYA.AdvanceUserEnterNotice,
    6203: HUYA.ViewerListRsp,
    6210: HUYA.VipBarListRsp,
    6220: HUYA.WeekRankListRsp,
    6221: HUYA.WeekRankEnterBanner,
    6223: HUYA.FansSupportListRsp,
    6230: HUYA.FansRankListRsp,
    6231: HUYA.BadgeInfo,
    6232: HUYA.BadgeScoreChanged,
    6233: HUYA.FansInfoNotice,
    6234: HUYA.UserGiftNotice,
    6235: HUYA.WeekStarPropsIds,
    6245: HUYA.kSecPackSuperFansExtendNotice,
    6250: HUYA.GiftBarRsp,
    6260: HUYA.GrandCeremonyChampionPresenter,
    6285: HUYA.LotteryPanel,
    6286: HUYA.LotteryData,
    6287: HUYA.LotteryAggreData,
    6288: HUYA.LotteryEndNotice,
    6289: HUYA.LotteryAnnounce,
    6290: HUYA.NewsTicker,
    6501: HUYA.SendItemSubBroadcastPacket,
    6502: HUYA.SendItemNoticeWordBroadcastPacket,
    6640: HUYA.ShowScreenSkinNotify,
    6641: HUYA.HideScreenSkinNotify,
    6291: HUYA.BannerNotice,
    6294: HUYA.OnTVPanel,
    6295: HUYA.OnTVPanel,
    6296: HUYA.OnTVData,
    6297: HUYA.OnTVEndNotice,
    6298: HUYA.OnTVBarrageNotice,
    6340: HUYA.CheckRoomStatus,
    6507: HUYA.SendItemNoticeGameBroadcastPacket,
    6602: HUYA.TreasureResultBroadcastPacket,
    6604: HUYA.TreasureUpdateNotice,
    6605: HUYA.TreasureLotteryResultNoticePacket,
    6616: HUYA.ItemLotterySubNotice,
    6617: HUYA.ItemLotteryGameNotice,
    7054: HUYA.MatchRaffleResultNotice,
    7055: HUYA.MatchRaffleResultNotice,
    7500: HUYA.BatchGameInfoNotice,
    7501: HUYA.GameInfoChangeNotice,
    7502: HUYA.EndHistoryGameNotice,
    7503: HUYA.GameSettlementNotice,
    7504: HUYA.PresenterEndGameNotice,
    7708: HUYA.PresenterLevelNotice,
    7709: HUYA.PresenterLevelNotice,
    8000: HUYA.BeginLiveNotice,
    8001: HUYA.EndLiveNotice,
    8002: HUYA.StreamSettingNotice,
    8004: HUYA.LiveInfoChangedNotice,
    8006: HUYA.AttendeeCountNotice,
    9010: HUYA.ReplayPresenterInLiveNotify,
    10040: HUYA.AuditorEnterLiveNotice,
    10041: HUYA.AuditorRoleChangeNotice,
    10042: HUYA.GetRoomAuditConfRsp,
    42008: HUYA.LinkMicStatusChangeNotice,
    44000: HUYA.InterveneCountRsp,
    1000106: HUYA.UserLevelUpgradeNotice,
    1000107: HUYA.UserNovieTaskCompleteNotice,
    1020001: HUYA.GuardianPresenterInfoNotice,
    1025300: HUYA.SupportCampInfoRsp,
    1025301: HUYA.UserSupportCampRsp,
    1025302: HUYA.UserSupportEffectRsp,
    1025305: HUYA.WSRedirect,
    10220251: HUYA.LiveAdvertisementNotice,
    // 10220054: HYUDB.UnionAuthPushMsg,
    1025000: HUYA.RMessageNotify,
    1025493: HUYA.PushPresenterAdNotice,
    1025307: HUYA.WSP2POpenNotify,
    1025308: HUYA.WSP2PCloseNotify,
    1025601: HUYA.LiveMeetingSyncNotice,
    1025604: HUYA.MakeFriendsPKInfo,
    1025605: HUYA.LiveRoomTransferNotice,
    1025800: HUYA.GetPugcVipListRsp,
    1025801: HUYA.PugcVipInfo,
    1030005: HUYA.GiftInventSmallPrizeInfoPush,
    1030006: HUYA.GiftInventSmallPrizeInfoPush,
    1030007: HUYA.GiftInventBigAwardRemainTimeInfo,
    1030008: HUYA.GiftInventBigAwardRemainTimeInfo,
    1030009: HUYA.GiftInventBigAwardPoolInfo,
    1030010: HUYA.GiftInventBigAwardPoolCountDown,
    1031001: HUYA.PrizeRecord,
    1031002: HUYA.PrizeRecord,
    1031003: HUYA.BoxScore,
    1031004: HUYA.BoxScoreV2,
    1033001: HUYA.PayLiveRoomNotice,
    1034001: HUYA.MatchEndNotice,
    // 2018103001: QAGuessWatchLive.QAGuessInfoPanel,
    // 2018103008: QAGuessWatchLive.QAGuessSettlePanel,
    // 2018103010: QAGuessWatchLive.QAGuessPreStartNotifyPanel,
    // 20180426: GUESS.GetDragonRsp,
    // 1010003: HUYA.ActivityMsgRsp,
    // 201908101: ActSuperFans.AnchorPanel,
    // 201908102: ActSuperFans.AnchorUpdate,
    // 201908103: ActSuperFans.TeamInfo,
    // 201908104: ActSuperFans.DaySupportRank,
    // 201908105: ActSuperFans.FansQuotaRank,
    // 201908106: ActSuperFans.ReliveRank,
    // 201908107: ActSuperFans.TeamPKInfo,
    // 201908108: ActSuperFans.BattlePanel,
    // 201908109: ActSuperFans.BattleScore,
    // 201908110: ActSuperFans.BattleResultPanel,
    // 201908111: ActSuperFans.PromoteResult,
    // 201908112: ActSuperFans.ResultPanel,
    // 201908113: ActSuperFans.ClearPanel,
    // 1040000: DEV.Message,
    // 1040002: DEV.Message,
    // 1029000: HUYA.MatchWebPushLiveRsp,
    // 1029001: HUYA.MatchRecLiveInfo,
    // 1029002: ActLiveCall.GetBattleTeamInfoRsp,
    // 1025312: MatchGuess.MatchCmdColorNotify,
    // 1010005: HUYA.ActivityTorMsgRsp,
    // 2018060701: ActWatchTor.AnchorPanel,
    // 2018060702: ActWatchTor.PublishHistoryRsp
});
Object.assign(TafMx.WupMapping, {
    OnUserEvent: HUYA.UserEventRsp,
    doLaunch: HUYA.LiveLaunchRsp,
    getLivingInfo: HUYA.GetLivingInfoRsp,
    getWebdbUserInfo: HUYA.GetWebdbUserInfoRsp,
    batchGetCdnTokenInfo: HUYA.BatchGetCdnTokenRsp,
    getPropsList: HUYA.GetPropsListRsp,
    getCurWeekStarPropsIds: HUYA.WeekStarPropsIds,
    sendCardPackageItem: HUYA.SendCardPackageItemRsp,
    getVerificationStatus: HUYA.GetVerificationStatusResp,
    getFirstRechargePkgStatus: HUYA.GetFirstRechargePkgStatusResp,
    getPresenterDetail: HUYA.GetPresenterDetailRsp,
    OnUserHeartBeat: HUYA.UserHeartBeatRsp,
    getCdnTokenInfoEx: HUYA.GetCdnTokenExRsp,
    getSequence: HUYA.GetSequenceRsp,
    getBatchPropsItem: HUYA.GetBatchPropsItemRsp,
    consumeGift: HUYA.ConsumeGiftRsp,
    consumeGiftSafe: HUYA.ConsumeGiftSafeRsp,
    getVipBarList: HUYA.VipBarListRsp,
    getWeekRankList: HUYA.WeekRankListRsp,
    muteRoomUser: HUYA.MuteRoomUserRsp,
    sendMessage: HUYA.SendMessageRsp,
    GetNobleInfo: HUYA.NobleInfoRsp,
    queryBadgeInfoList: HUYA.BadgeInfoListRsp,
    queryBadgeInfo: HUYA.BadgeInfo,
    useBadge: HUYA.BadgeInfo,
    getVipCard: HUYA.VipCardRsp,
    getScreenSkin: HUYA.getScreenSkinRsp,
    getRoomAuditConf: HUYA.GetRoomAuditConfRsp,
    getUserLevelInfo: HUYA.GetUserLevelInfoRsp,
    getViewerList: HUYA.ViewerListRsp,
    getFansSupportList: HUYA.FansSupportListRsp,
    sendReplayMessage: HUYA.SendReplayMessageRsp,
    getPresenterActivity: HUYA.PresenterActivityRsp,
    getRMessageList: HUYA.GetRMessageListRsp,
    getRMessageListWb: HUYA.GetRMessageListRsp,
    getDirectorProgramList: HUYA.GetDirectorProgramListRsp,
    getSuperFansCard: HUYA.GetSuperFansCardRsp,
    getSuperFansRankList: HUYA.SuperFansRankListRsp,
    reportMessage: HUYA.ReportMessageRsp,
    getUserBoxInfo: HUYA.GetUserBoxInfoRsp,
    finishTaskNotice: HUYA.FinishTaskNoticeRsp,
    awardBoxPrize: HUYA.AwardBoxPrizeRsp,
    getTreasureBoxInfo: HUYA.GetTreasureBoxInfoRsp,
    bet: HUYA.BetRsp,
    buyBet: HUYA.BuyBetRsp,
    getGameInfo: HUYA.GetGameInfoListRsp,
    getRemainBeanNum: HUYA.GetRemainBeanNumRsp,
    getAssistant: HUYA.GetAssistantRsp,
    queryCardPackage: HUYA.QueryCardPackageRsp,
    queryTreasure: HUYA.QueryTreasureInfoRsp,
    sendTreasureLotteryDraw: HUYA.TreasureLotteryDrawRsp,
    getLinkMicPresenterListByUid: HUYA.GetLinkMicPresenterInfoRsp,
    subscribe: HUYA.SubscribeResp,
    unsubscribe: HUYA.UnsubscribeResp,
    getSubscribeStatus: HUYA.SubscribeStatusResp,
    getRelation: HUYA.GetRelationRsp,
    addSubscribe: HUYA.ModRelationRsp,
    delSubscribe: HUYA.ModRelationRsp,
    getRelationBatch: HUYA.GetRelationBatchRsp,
    isPugcRoom: HUYA.IsPugcRoomRsp,
    getPugcVipList: HUYA.GetPugcVipListRsp,
    getGameLiveHisUpon: HUYA.GetGameLiveHisUponRsp,
    getVideoHisUpon: HUYA.GetGameLiveHisUponRsp,
    getBadgeName: HUYA.BadgeNameRsp,
    getBadgeNameV2: HUYA.BadgeNameRsp,
    getLiveAdInfo: HUYA.GetLiveAdInfoRsp,
    getAuditorRole: HUYA.AuditorEnterLiveNotice,
    getBadgeConfigInfo: HUYA.BadgeConfigInfoRsp,
    getCustomBadgeLogo: HUYA.CustomBadgeLogoRsp,
    setBadgeV: HUYA.SetBadgeVRsp,
    setUserProfile: HUYA.SetUserProfileRsp,
    getMaiXuBySid: HUYA.MaiXuSearchRsp,
    getOnTVPanel: HUYA.OnTVPanel,
    getOnTVUserInfo: HUYA.OnTVUserInfoRsp,
    sendOnTVBarrage: HUYA.SendOnTVBarrageRsp,
    getBadgeItem: HUYA.BadgeItemRsp,
    getCurrentGameAd: HUYA.GameAdvertisement,
    getSupportCampInfo: HUYA.SupportCampInfoRsp,
    getUserSupportCamp: HUYA.UserSupportCampRsp,
    getUserSetting: HUYA.SettingFetchRsp,
    getLotteryPanel: HUYA.LotteryPanel,
    getLotteryUserInfo: HUYA.LotteryUserInfoRsp,
    buyTicket: HUYA.BuyTicketRsp,
    getBoxPanelInfo: HUYA.GetBoxPanelInfoRsp,
    getUserPrizeRecordList: HUYA.UserPrizeRecordListRsp,
    getAwardPoolPanelInfo: HUYA.GiftInventGetPanelInfoRsp,
    getGiftInventRankList: HUYA.GetGiftInventRankListRsp,
    getPresenterLiveScheduleInfo: HUYA.GetPresenterLiveScheduleInfoRsp,
    getPresenterLevelBase: HUYA.PresenterLevelBaseRsp,
    getPresenterLevelProgress: HUYA.PresenterLevelProgressRsp,
    getActivityMsg: HUYA.ActivityMsgRsp,
    GetCurCheckRoomStatus: HUYA.CheckRoomStatus,
    CKRoomUserEnter: HUYA.CheckRoomRsp,
    getFansPrivilege: HUYA.FansPrivilegeRsp,
    queryBadgeInfoV2: HUYA.BadgeInfo,
    useBadgeV2: HUYA.BadgeInfo,
    // getDragonInfo: GUESS.GetDragonRsp,
    getActivityTorMsg: HUYA.ActivityTorMsgRsp,
    // getTorMemberTaskResult: ActWatchTor.MemberTaskResultRsp,
    // startTorPublishTask: ActWatchTor.PublishTaskRsp,
    // getTorPublishPanel: ActWatchTor.PublishPanelRsp,
    // queryTorWeekHistory: ActWatchTor.PublishHistoryRsp,
    // getTeamMemberInfo: ActSuperFans.TeamInfo,
    // GetBattleTeamInfo: ActLiveCall.GetBattleTeamInfoRsp,
    getMeetingStatByPresenterUid: HUYA.GetMeetingStatByUidRsp,
    getMakeFriendsPKInfo: HUYA.GetMakeFriendsPKInfoRsp,
    getMakeFriendsAnnouncement: HUYA.GetMakeFriendsAnnouncementRsp,
    getPresenterMomentFeed: HUYA.GetPresenterMomentFeedRsp,
    // getUserPanel: QAGuessWatchLive.QAGuessGetUserPanelRsp,
    getPresenterAd: HUYA.GetPresenterAdRsp,
    getDIYActivityInfo: HUYA.ActivityDIYRsp,
    getRctTimedMessage: HUYA.GetRctTimedMessageRsp,
    getWBAudienceShare: HUYA.WBAudienceShareRsp,
    getJWT: HUYA.GetJWTResp,
    getUserExtAuthorizeInfo: HUYA.GetUserExtAuthorizeResp,
    userExtAuthorize: HUYA.UserExtAuthorizeResp,
    getProfileExtList: HUYA.GetProfileExtListResp,
    routeEbsRequest: HUYA.RouteEBSResp,
    setStorage: HUYA.SetStorageResp,
    getStorageKey: HUYA.GetStorageKeyResp,
    delStorageKey: HUYA.DelStorageKeyResp,
    getStorageAllKeys: HUYA.GetStorageAllKeysResp,
    deliverRoomMsgByUnionId: HUYA.DeliverRoomMsgByUnionIdResp,
    textReportSDKFormExt: HUYA.TextReportSDKFormExtResp,
    getPicUploadPolicy: HUYA.GetPicUploadPolicyResp,
    routeEbsRequestV2: HUYA.RouteEBSV2Resp,
    enterPayLiveRoom: HUYA.EnterPayLiveRoomRsp,
    subscribePayLiveRoom: HUYA.SubscribePayLiveRoomRsp,
    getPayLiveRoomInfo: HUYA.GetPayLiveRoomInfoRsp,
    getExpressionEmoticonPackage: HUYA.GetExpressionEmoticonPackageRsp,
    sendExpressionEmoticon: HUYA.SendExpressionEmoticonRsp
});
Object.assign(TafMx.NoLog, {
    1400: 1,
    6298: 1,
    6501: 1,
    7501: 1,
    1010003: 1,
    OnUserHeartBeat: 1,
    videoClientReport: 1
});

module.exports =  TafMx;